name: "Depends check 260903"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    name: Experimental 260903
    runs-on: ubuntu-latest
    steps:
      - name: Build and test on OpenBSD
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.9"
          mem: 8192
          prepare: |
            pkg_add -Uu
            pkg_add git cmake ninja gmake python%3 rust openssl%3.5
          run: |
            set -e
            wheel=$PWD/curl_cffi-0.16.3-cp310-abi3-openbsd_7_9_amd64.openbsd_8_0_amd64.whl
            ftp https://github.com/c2qd/curl_cffi_ci/releases/download/r3/curl_cffi-0.16.3-cp310-abi3-openbsd_7_9_amd64.openbsd_8_0_amd64.whl

            git clone https://github.com/lexiforest/curl_cffi
            cd curl_cffi
            git checkout tags/v0.16.3

            python3 -m venv .testvenv
            . .testvenv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install $wheel
            env OPENSSL_INCLUDE_DIR="/usr/local/include/eopenssl35" OPENSSL_LIB_DIR="/usr/local/lib/eopenssl35" python3 -m pip install $(python3 -c "import tomllib; print(' '.join(tomllib.load(open('pyproject.toml', 'rb'))['project']['optional-dependencies']['test']))")
            cucf_root=$PWD
            cd
            python3 -bb -m pytest $cucf_root/tests/unittest --ignore=$cucf_root/tests/unittest/test_async_websockets.py
            deactivate
