name: "Build and test on OpenBSD"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  REV: 3
  CURL_IMPERSONATE_VERSION: 2.2.2
  CURL_CFFI_VERSION: 0.16.3

jobs:
  build-test:
    name: (${{ matrix.host_label }}) Build and test curl-impersonate / curl_cffi
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - vm_arch: x86_64
            host_label: x86_64-openbsd
            platform_tag: amd64
          - vm_arch: aarch64
            host_label: aarch64-openbsd
            platform_tag: aarch64
          - vm_arch: riscv64
            host_label: riscv64-openbsd
            platform_tag: riscv64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Build and test on OpenBSD
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.9"
          mem: 8192
          arch: ${{ matrix.vm_arch }}
          prepare: |
            pkg_add -Uu
            pkg_add git cmake ninja gmake python%3
            if [ "${{ matrix.vm_arch }}" = "x86_64" ]; then
              pkg_add rust openssl%3.5 gsed
            fi
          run: |
            set -e
            git clone https://github.com/lexiforest/curl-impersonate
            cd curl-impersonate
            git checkout tags/v${{ env.CURL_IMPERSONATE_VERSION }}
            install_dir="$PWD/openbsd-install"
            artifacts_dir="$PWD/openbsd-artifacts"
            rm -rf build-openbsd "$install_dir" "$artifacts_dir"
            mkdir -p "$install_dir" "$artifacts_dir"

            patch < ../curl-impersonate.patch
            cmake_args="-G Ninja -DCMAKE_INSTALL_PREFIX=$install_dir"
            gmake configure BUILD_DIR=build-openbsd CMAKE_CONFIGURE_ARGS="$cmake_args"
            gmake build BUILD_DIR=build-openbsd CMAKE_CONFIGURE_ARGS="$cmake_args"

            v="$(build-openbsd/deps/build/curl/src/curl-impersonate -V)"
            for feature in zlib zstd brotli nghttp2 BoringSSL; do
              echo "$v" | grep -q "$feature"
            done

            gmake install-strip BUILD_DIR=build-openbsd CMAKE_CONFIGURE_ARGS="$cmake_args"

            install_lib_dir="$install_dir/lib"
            deps_lib_dir="$PWD/build-openbsd/deps/install/lib"

            cp "$deps_lib_dir/libz.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libzstd.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libbrotlidec.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libbrotlicommon.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libbrotlienc.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libnghttp2.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libnghttp3.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libngtcp2.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libngtcp2_crypto_boringssl.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libssl.a" "$install_lib_dir/"
            cp "$deps_lib_dir/libcrypto.a" "$install_lib_dir/"

            cd "$install_lib_dir"
            mv libcurl-impersonate.a libcurl-impersonate.orig.a
            cc -r -o libcurl-impersonate.full.o -Wl,--whole-archive \
              libcurl-impersonate.orig.a libz.a libzstd.a \
              libbrotlidec.a libbrotlicommon.a libbrotlienc.a \
              libnghttp2.a libnghttp3.a libngtcp2.a \
              libngtcp2_crypto_boringssl.a libssl.a libcrypto.a \
              -Wl,--no-whole-archive
            ar rcs libcurl-impersonate.a libcurl-impersonate.full.o
            rm -f libcurl-impersonate.full.o
            rm -f libz.a libzstd.a libbrotlidec.a libbrotlicommon.a libbrotlienc.a libnghttp2.a libnghttp3.a libngtcp2.a libngtcp2_crypto_boringssl.a libssl.a libcrypto.a
            rm -f libcurl-impersonate.orig.a

            tar -czf "$artifacts_dir/libcurl-impersonate-${{ env.CURL_IMPERSONATE_VERSION }}.${{ matrix.host_label }}.tar.gz" lib* -C "$install_dir" include LICENSE LICENSE_BORINGSSL LICENSE_BROTLI LICENSE_CURL LICENSE_NGHTTP2 LICENSE_NGHTTP3 LICENSE_NGTCP2 LICENSE_ZLIB LICENSE_ZSTD

            cd "$install_dir/bin"
            tar -czf "$artifacts_dir/curl-impersonate-${{ env.CURL_IMPERSONATE_VERSION }}.${{ matrix.host_label }}.tar.gz" curl-impersonate curl_*

            cd ../../..
            git clone https://github.com/lexiforest/curl_cffi
            cd curl_cffi
            git checkout tags/v${{ env.CURL_CFFI_VERSION }}
            patch < ../curl_cffi.patch
            python3 -m venv .buildvenv
            . .buildvenv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install build wheel
            env CFLAGS="-I$install_dir/include" IMPERSONATE_BUILD_DIR=$install_lib_dir python3 -m build -w
            # Compat with -current
            python3 -m wheel tags --platform-tag="+openbsd_8_0_${{ matrix.platform_tag }}" --remove dist/*.whl
            deactivate

            if [ "${{ matrix.vm_arch }}" = "x86_64" ]; then
              python3 -m venv .testvenv
              . .testvenv/bin/activate
              python3 -m pip install --upgrade pip
              python3 -m pip install dist/*.whl
              env OPENSSL_INCLUDE_DIR="/usr/local/include/eopenssl35" OPENSSL_LIB_DIR="/usr/local/lib/eopenssl35" python3 -m pip install $(python3 -c "import tomllib; print(' '.join(tomllib.load(open('pyproject.toml', 'rb'))['project']['optional-dependencies']['test']))")
              cucf_root=$PWD
              cd /tmp
              python3 -bb -m pytest $cucf_root/tests/unittest --ignore=$cucf_root/tests/unittest/test_async_websockets.py
              deactivate
            fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts.${{ matrix.host_label }}
          path: |
            curl-impersonate/openbsd-artifacts/*.tar.gz
            curl_cffi-${{ env.CURL_CFFI_VERSION }}/dist/*.whl
  release:
    name: Create GitHub Release
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: artifacts.*
          path: release-assets
          merge-multiple: true

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "r${{ env.REV }}" \
            --title "r${{ env.REV }}: ${{ env.CURL_IMPERSONATE_VERSION }}+${{ env.CURL_CFFI_VERSION }}" \
            --generate-notes \
            release-assets/curl-impersonate/openbsd-artifacts/*.tar.gz \
            release-assets/curl_cffi/dist/*.whl
