name: "Build and test on OpenBSD"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  REV: 3
  CURL_IMPERSONATE_VERSION: 2.2.2
  CURL_CFFI_VERSION: 0.16.3b1

jobs:
  build-test:
    name: (${{ matrix.host_label }}) Build and test curl_cffi
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - vm_arch: x86_64
            host_label: x86_64-openbsd
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Build and test on OpenBSD
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.9"
          mem: 8192
          arch: ${{ matrix.vm_arch }}
          # rust/openssl/(gsed?): test deps
          prepare: |
            pkg_add -Uu
            pkg_add git python%3 rust openssl%3.5 gsed
          run: |
            ftp https://github.com/c2qd/curl_cffi_ci/releases/download/r2/libcurl-impersonate-${{ env.CURL_IMPERSONATE_VERSION }}.${{ matrix.host_label }}.tar.gz
            mkdir libcurl-impersonate
            tar xzf libcurl-impersonate-${{ env.CURL_IMPERSONATE_VERSION }}.${{ matrix.host_label }}.tar.gz -C libcurl-impersonate
            git clone https://github.com/lexiforest/curl_cffi
            cd curl_cffi
            git checkout tags/v${{ env.CURL_CFFI_VERSION }}
            patch < ../curl_cffi.patch
            python3 -m venv .buildvenv
            . .buildvenv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install build wheel
            env CFLAGS="-I../libcurl-impersonate/include" IMPERSONATE_BUILD_DIR="../libcurl-impersonate" python3 -m build -w
            deactivate

            python3 -m venv .testvenv
            . .testvenv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install dist/*.whl
            env OPENSSL_INCLUDE_DIR="/usr/local/include/eopenssl35" OPENSSL_LIB_DIR="/usr/local/lib/eopenssl35" python3 -m pip install "charset_normalizer>=3.3.2,<4.0" "cryptography>=46.0.4,<47.0" "litestar>=2.19.0,<3.0" "httpx==0.23.1" "proxy.py>=2.4.3,<3.0" "pytest>=8.1.1,<9.0" "pytest-asyncio>=0.23.6,<1.0" "pytest-trio>=0.8.0,<1.0" "python-multipart>=0.0.9,<1.0" "trio>=0.25.0,<1.0" "trustme>=1.1.0,<2.0" "uvicorn>=0.29.0,<1.0" "websockets>=14.0" "typing_extensions"
            curl_cffi_root=$PWD
            cd /tmp
            python3 -bb -m pytest ${curl_cffi_root}/tests/unittest
            curl-cffi doctor
            deactivate
