name: "Build maturin and cryptography"

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  MATURIN_OPENSSL_SYS_VERSION: 0.9.116
  CRYPTOGRAPHY_OPENSSL_SYS_VERSION: 0.9.110

jobs:
  build:
    name: Build maturin and cryptography
    runs-on: ubuntu-latest
    steps:
      - name: Build on OpenBSD
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.9"
          mem: 8192
          arch: x86_64
          prepare: |
            pkg_add -Uu
            pkg_add python%3 rust
          run: |
            set -e
            for ver in ${{ env.MATURIN_OPENSSL_SYS_VERSION }} ${{ env.CRYPTOGRAPHY_OPENSSL_SYS_VERSION }}; do
              cd ${{ github.workspace }}
              ftp https://static.crates.io/crates/openssl-sys/openssl-sys-$ver.crate
              tar xzf openssl-sys-$ver.crate
              cd openssl-sys-$ver
              # https://github.com/libressl/portable/blob/master/.github/workflows/rust-openssl.yml
              ed -s build/main.rs << 'EOF'
            /_ => version_error/-1
            .t.
            s/(.*=/_ =
            +1d
            w
            q
            EOF
            done

            mkdir -p "${{ github.workspace }}/.cargo_maturin" "${{ github.workspace }}/.cargo_cryptography"
            cat << 'EOF' >> "${{ github.workspace }}/.cargo_maturin/config.toml"
            [patch.crates-io]
            openssl-sys = { path = "${{ github.workspace }}/openssl-sys-${{ env.MATURIN_OPENSSL_SYS_VERSION }}", package = "openssl-sys" }
            EOF
            cat << 'EOF' >> "${{ github.workspace }}/.cargo_cryptography/config.toml"
            [patch.crates-io]
            openssl-sys = { path = "${{ github.workspace }}/openssl-sys-${{ env.CRYPTOGRAPHY_OPENSSL_SYS_VERSION }}", package = "openssl-sys" }
            EOF

            cd ${{ github.workspace }}
            python3 -m venv .venv
            . .venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install wheel build
            python3 -m pip download --no-binary maturin --no-binary cryptography maturin "cryptography>=46.0.4,<47.0"
            tar xzf maturin-*.tar.gz
            tar xzf cryptography-*.tar.gz
            rm maturin-*.tar.gz cryptography-*.tar.gz
            mv maturin-* maturin
            mv cryptography-* cryptography
            cd maturin
            env CARGO_HOME="${{ github.workspace }}/.cargo_maturin" cargo update -p openssl-sys --precise ${{ env.MATURIN_OPENSSL_SYS_VERSION }}
            env CARGO_HOME="${{ github.workspace }}/.cargo_maturin" python3 -m pip wheel . -w .
            python3 -m pip install maturin*.whl
            rm -rf "${{ github.workspace }}/.cargo_maturin"
            cd ${{ github.workspace }}/cryptography
            env CARGO_HOME="${{ github.workspace }}/.cargo_cryptography" cargo update --manifest-path src/rust/Cargo.toml -p openssl-sys --precise ${{ env.CRYPTOGRAPHY_OPENSSL_SYS_VERSION }}
            env CARGO_HOME="${{ github.workspace }}/.cargo_cryptography" python3 -m build --wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: |
            maturin/*.whl
            cryptography/dist/*.whl
