name: "Build with MinGW-w64 and test"

on:
  workflow_dispatch:

permissions: {}

env:
  LLVM_MINGW_V: "20260922"
  GCC_MINGW_V: "gcc-16"
  PR336_COMMIT: 190caf97aec24cff22bad563ee26e873c8cc07c5

jobs:
  build:
    name: Build on Ubuntu (${{ matrix.toolchain }}, ${{ matrix.arch }})
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        arch: [x86_64, i686, aarch64, armv7]
        toolchain: [clang, gcc]
        exclude:
          - arch: armv7
            toolchain: gcc
    env:
      MINGW_TOOLCHAIN: "${{ matrix.toolchain }}"
      MINGW_ARCH: "${{ matrix.arch }}"
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make cmake ninja-build curl xz-utils git
          if [ "${{ matrix.arch }}" = "x86_64" ] || [ "${{ matrix.arch }}" = "i686" ]; then
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install nasm wine wine64 wine32
          fi

      - name: Install MinGW toolchain
        run: |
          if [ "${{ matrix.toolchain }}" = "clang" ]; then
            curl -fsSL -o llvm-mingw.tar.xz https://github.com/mstorsjo/llvm-mingw/releases/download/${{ env.LLVM_MINGW_V }}/llvm-mingw-${{ env.LLVM_MINGW_V }}-ucrt-ubuntu-22.04-x86_64.tar.xz
            sudo mkdir -p /opt/llvm-mingw
            sudo tar -xJf llvm-mingw.tar.xz --strip-components=1 -C /opt/llvm-mingw
          elif [ "${{ matrix.toolchain }}" = "gcc" ]; then
            curl -fsSL -o gcc-mingw.tar.xz https://github.com/AmanoTeam/mingw-gcc-cross/releases/download/${{ env.GCC_MINGW_V }}/x86_64-unknown-linux-gnu.tar.xz
            sudo mkdir -p /opt/gcc-mingw
            sudo tar -xJf gcc-mingw.tar.xz --strip-components=1 -C /opt/gcc-mingw
          fi

      - name: Build
        run: |
          git clone https://github.com/c2qd/curl-impersonate.git
          cd curl-impersonate
          git switch feature/mingw
          git cherry-pick --no-commit ${{ env.PR336_COMMIT }}
          if [ "${{ matrix.toolchain }}" = "clang" ]; then
            export MINGW_ROOT="/opt/llvm-mingw"
          elif [ "${{ matrix.toolchain }}" = "gcc" ]; then
            export MINGW_ROOT="/opt/gcc-mingw"
          fi
          export CMAKE_CONFIGURE_ARGS="-DCMAKE_INSTALL_PREFIX=./install"
          export USE_WINE=1
          ./scripts/mingw.sh build
          if [ "${{ matrix.arch }}" == "x86_64" ] || [ "${{ matrix.arch }}" == "i686" ]; then
            ./scripts/mingw.sh checkbuild
          fi
          ./scripts/mingw.sh install-strip
          tar -C install -czf "curl-impersonate.tgz" .

      - name: Upload artifact
        if: ${{ ! (matrix.toolchain == 'clang' && matrix.arch == 'armv7') }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts.ubuntu.${{ matrix.arch }}.${{ matrix.toolchain }}
          path: curl-impersonate/curl-impersonate.tgz

  build-w:
    name: Build on Windows (${{ matrix.toolchain }}, ${{ matrix.arch }}, ${{ matrix.script }})
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, i686, aarch64]
        toolchain: [clang, gcc]
        script: [sh, bat]
        exclude:
          - arch: aarch64
            toolchain: gcc
    env:
      MINGW_ARCH: ${{ matrix.arch }}
      MINGW_TOOLCHAIN: ${{ matrix.toolchain }}
    steps:
      - name: Install dependencies
        shell: pwsh
        run: |
          if ("${{ matrix.script }}" -eq "sh") {
            choco install make
          }
          if ("${{ matrix.arch }}" -eq "x86_64" -or "${{ matrix.arch }}" -eq "i686") {
            choco install nasm
          }

      - name: Install MinGW toolchain
        shell: pwsh
        run: |
          mkdir toolchain
          cd toolchain
          if ("${{ matrix.toolchain }}" -eq "clang") {
            Invoke-WebRequest -Uri https://github.com/mstorsjo/llvm-mingw/releases/download/${{ env.LLVM_MINGW_V }}/llvm-mingw-${{ env.LLVM_MINGW_V }}-ucrt-x86_64.zip -OutFile llvm-mingw.zip
            7z x llvm-mingw.zip
            $path = (Get-ChildItem -Directory -Path .\llvm-mingw-* | Select-Object -First 1).FullName
          } elseif ("${{ matrix.toolchain }}" -eq "gcc") {
            $exception = if ("${{ matrix.arch }}" -eq "i686") {
              "dwarf"
            } elseif ("${{ matrix.arch }}" -eq "x86_64") {
                "seh"
            }
            Invoke-WebRequest -Uri https://github.com/niXman/mingw-builds-binaries/releases/download/${{ env.GCC_V }}-${{ env.GCC_MINGW_V }}/${{ matrix.arch }}-${{ env.GCC_V }}-release-win32-$exception-ucrt-${{ env.GCC_MINGW_V }}.7z -OutFile gcc-mingw.7z
            7z x gcc-mingw.7z
            $path = (Get-ChildItem -Directory -Filter 'mingw*' | Select-Object -First 1).FullName
          }

          if ("${{ matrix.script }}" -eq "sh") {
            $path = $path -replace '^([A-Za-z]):', '/$1' -replace '\\', '/'
          }
          echo "MINGW_ROOT=$path" >> $env:GITHUB_ENV

      - name: Clone the repo
        shell: pwsh
        run: |
          git clone https://github.com/c2qd/curl-impersonate.git
          cd curl-impersonate
          git switch feature/mingw
          git cherry-pick --no-commit $env:PR336_COMMIT

      - name: Build via scripts/mingw.sh
        if: matrix.script == 'sh'
        shell: bash
        run: |
          cd curl-impersonate
          export CMAKE_CONFIGURE_ARGS="-DCMAKE_INSTALL_PREFIX=./packages"
          ./scripts/mingw.sh build
          if [ "${{ matrix.arch }}" = "x86_64" ] || [ "${{ matrix.arch }}" = "i686" ]; then
            ./scripts/mingw.sh checkbuild
          fi
          ./scripts/mingw.sh install-strip

      - name: Build via win/mingw-build.bat
        if: matrix.script == 'bat'
        shell: pwsh
        run: |
          cd curl-impersonate
          .\win\mingw-build.bat ${{ matrix.toolchain }} ${{ matrix.arch }} "$env:MINGW_ROOT"

      - name: Make tarball
        shell: pwsh
        run: |
          cd curl-impersonate
          tar -C packages -czf curl-impersonate.tgz .

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts.windows-${{ matrix.script }}.${{ matrix.arch }}.${{ matrix.toolchain }}
          path: curl-impersonate/curl-impersonate.tgz

  test:
    name: Test (${{ matrix.built_on }}, ${{ matrix.toolchain }}, ${{ matrix.arch }})
    needs: [build, build-w]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - built_on: ubuntu
            arch: x86_64
            toolchain: clang
            os: windows-latest
          - built_on: ubuntu
            arch: x86_64
            toolchain: gcc
            os: windows-latest
          - built_on: ubuntu
            arch: i686
            toolchain: clang
            os: windows-latest
          - built_on: ubuntu
            arch: i686
            toolchain: gcc
            os: windows-latest
          - built_on: ubuntu
            arch: aarch64
            toolchain: clang
            os: windows-11-arm
          - built_on: windows-bat
            arch: x86_64
            toolchain: clang
            os: windows-latest
          - built_on: windows-sh
            arch: x86_64
            toolchain: clang
            os: windows-latest
          - built_on: windows-bat
            arch: x86_64
            toolchain: gcc
            os: windows-latest
          - built_on: windows-sh
            arch: x86_64
            toolchain: gcc
            os: windows-latest
          - built_on: windows-bat
            arch: i686
            toolchain: clang
            os: windows-latest
          - built_on: windows-sh
            arch: i686
            toolchain: clang
            os: windows-latest
          - built_on: windows-bat
            arch: i686
            toolchain: gcc
            os: windows-latest
          - built_on: windows-sh
            arch: i686
            toolchain: gcc
            os: windows-latest
          - built_on: windows-bat
            arch: aarch64
            toolchain: clang
            os: windows-11-arm
          - built_on: windows-sh
            arch: aarch64
            toolchain: clang
            os: windows-11-arm
    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifacts.${{ matrix.built_on }}.${{ matrix.arch }}.${{ matrix.toolchain }}

      - name: Extract
        shell: bash
        run: |
          tar -xzf curl-impersonate.tgz

      - name: Test
        shell: pwsh
        run: |
          .\bin\curl-impersonate.exe -V
          foreach ($wrapper in Get-ChildItem bin\*.bat) {
            echo $wrapper.FullName
            & $wrapper.FullName --ca-native https://tls.browserleaks.com
            if ($LASTEXITCODE -ne 0) {
              exit $LASTEXITCODE
            }
          }

  rm-artifacts:
    if: always()
    needs: test
    runs-on: ubuntu-26.04
    permissions:
      actions: write
    steps:
      - name: Remove artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
          --paginate \
          "/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts?per_page=100" \
          --jq '.artifacts[].id' |
          while read -r id; do
            gh api \
            --method DELETE \
            "/repos/${{ github.repository }}/actions/artifacts/$id"
          done
